parameters:
  - name: enviroment
    displayName: ENVIROMENT
    type: string
    default: dev
    values:
      - dev
      - prod

pool: test-pool
trigger: none

stages:
  - stage: terraforminit
    displayName: TERRAFORM INIT
    jobs:
      - job: InitJob
        displayName: "Init Job"
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              backendServiceArm: 'todo-svc-test'
              backendAzureRmStorageAccountName: 'azurepipeline123'
              backendAzureRmContainerName: 'azure'
              backendAzureRmKey: '${{ parameters.enviroment }}.terraform.tfstate'

  # similarly for other stages/jobs...
