# 

parameters:
  - name: enviroment
    displayName: ENVIRONMENT
    type: string
    default: dev
    values:
      - dev
      - prod

variables:
  - name: dev_svc
    value: 'dev-svc-todo'
  - name: prod_svc
    value: 'todo-svc-prod'

  - name: selected_svc
    ${{ if eq(parameters.enviroment, 'prod') }}:
      value: 'todo-svc-prod'
    ${{ if ne(parameters.enviroment, 'prod') }}:
      value: 'dev-svc-todo'

pool:
  name: test-pool

trigger: none

stages:
  - stage: terraforminit
    displayName: TERRAFORM INIT
    jobs:
      - job: InitJob
        displayName: "Init Job"
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              backendServiceArm: '$(selected_svc)'

  - stage: terraformplan
    displayName: TERRAFORM PLAN
    dependsOn: terraforminit
    jobs:
      - job: TerraformPlan
        displayName: "Terraform Plan Job"
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              environmentServiceNameAzureRM: '$(selected_svc)'

  - stage: terraformapply
    displayName: TERRAFORM APPLY
    dependsOn: terraformplan
    jobs:
      - job: TerraformApply
        displayName: "Terraform Apply Job"
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              environmentServiceNameAzureRM: '$(selected_svc)'
