parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: dev
    values:
      - dev
      - prod

variables:
  dev_service_connection: "dev-svc-todo"
  dev_storage_account: "devtodo"
  dev_container: "todo-dev-cont"

  prod_service_connection: "todo-svc-prod"
  prod_storage_account: "azurepipeline123"
  prod_container: "azure"

pool: test-pool
trigger: none

stages:
  - stage: terraform_init
    displayName: "Terraform Init"
    variables:
      service_connection: ${{ parameters.environment == 'dev' && variables.dev_service_connection || variables.prod_service_connection }}
      storage_account: ${{ parameters.environment == 'dev' && variables.dev_storage_account || variables.prod_storage_account }}
      container_name: ${{ parameters.environment == 'dev' && variables.dev_container || variables.prod_container }}
    jobs:
      - job: init
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              backendServiceArm: $(service_connection)
              backendAzureRmStorageAccountName: $(storage_account)
              backendAzureRmContainerName: $(container_name)
              backendAzureRmKey: '${{ parameters.environment }}.tfstate'

  - stage: terraform_plan
    displayName: "Terraform Plan"
    variables:
      service_connection: ${{ parameters.environment == 'dev' && variables.dev_service_connection || variables.prod_service_connection }}
      storage_account: ${{ parameters.environment == 'dev' && variables.dev_storage_account || variables.prod_storage_account }}
      container_name: ${{ parameters.environment == 'dev' && variables.dev_container || variables.prod_container }}
    jobs:
      - job: plan
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              backendServiceArm: $(service_connection)
              backendAzureRmStorageAccountName: $(storage_account)
              backendAzureRmContainerName: $(container_name)
              backendAzureRmKey: '${{ parameters.environment }}.tfstate'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              environmentServiceNameAzureRM: $(service_connection)

  - stage: terraform_apply
    displayName: "Terraform Apply"
    variables:
      service_connection: ${{ parameters.environment == 'dev' && variables.dev_service_connection || variables.prod_service_connection }}
      storage_account: ${{ parameters.environment == 'dev' && variables.dev_storage_account || variables.prod_storage_account }}
      container_name: ${{ parameters.environment == 'dev' && variables.dev_container || variables.prod_container }}
    jobs:
      - job: apply
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              backendServiceArm: $(service_connection)
              backendAzureRmStorageAccountName: $(storage_account)
              backendAzureRmContainerName: $(container_name)
              backendAzureRmKey: '${{ parameters.environment }}.tfstate'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              environmentServiceNameAzureRM: $(service_connection)
