parameters:
  - name: environment
    displayName: "ENVIRONMENT"
    type: string
    default: dev
    values:
      - dev
      - prod

variables:
  # Service Connection set based on environment
  - name: serviceConnection
    ${{ if eq(parameters.environment, 'prod') }}:
      value: 'todo-svc-prod'
    ${{ if eq(parameters.environment, 'dev') }}:
      value: 'dev-svc-todo'

pool: test-pool
trigger: none

stages:
  - stage: terraforminit
    displayName: TERRAFORM INIT
    jobs:
      - job: InitJob
        steps:
          - task: TerraformTask@5
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: 'rg-todo'     # optional if needed
              backendAzureRmStorageAccountName: ''
              backendAzureRmContainerName: ''
              backendAzureRmKey: ''
              commandOptions: >
                -backend-config=env/${{ parameters.environment }}/backend.tfvars

  - stage: terraformplan
    displayName: TERRAFORM PLAN
    jobs:
      - job: terraformplan
        steps:
          - task: TerraformTask@5
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              environmentServiceNameAzureRM: $(serviceConnection)
              commandOptions: >
                -var-file=env/${{ parameters.environment }}/backend.tfvars

  - stage: terraformapply
    displayName: TERRAFORM APPLY
    jobs:
      - job: terraformapply
        steps:
          - task: TerraformTask@5
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.environment }}'
              environmentServiceNameAzureRM: $(serviceConnection)
              commandOptions: >
                -var-file=env/${{ parameters.environment }}/backend.tfvars
